### ISSUE TITLE
EOF encountered polling device

### ISSUE THREAD

**Issue by dstrickler** [FlyingDiver/Indigo-TankUtility#1]
FlyingDriver,

Thank you so much for creating this code. It's been on my ToDo list since December, and I'm glad you beat me to it!

So I'm running the code for the first time this morning and got this error. I didn't look into your code for the problem, but thought I'd log it first here. Let me know if you need any debugging from my side.

```
Schedule                        TankUtility daily update & daily processing
TankUtility                     Getting tank data from TankUtility server...
TankUtility Debug               tuLogin failure, request url = https://data.tankutility.com/api/getToken
TankUtility Error               tuLogin failure, RequestException: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
TankUtility Debug               getDevices: TankUtility Login Failure
```

**Comment by FlyingDiver** [comment]
If you do a status request on that device what happens?  My guess is that this was a server failure on their side and there's nothing the plugin can do except try again.  Which I wouldn't want to do immediately after the failure since that would likely get the same error again.

FWIW, my daily update last night (1am EDT) had no issues.

**Comment by dstrickler** [comment]
The same error happens when I update the device, but I think I just found the issue. In their mobile app, I show the "Last Reading Date" as Aug 1st - 19 days ago. I'm going to investigate on my end and see if I can fix that. Then I'll check your plugin again.

**Comment by FlyingDiver** [comment]
Sounds good, thanks for the update.

**Comment by dstrickler** [comment]
The portal for the tank was completely filled with dirt, probably from the epic rains we got a few weeks ago. Enclosed is before and after pictures for some humor, of me digging around it. I hope to get a new reading today and let you know.

As a side note, it would be a neat feature if you could poll for the "Last Reading Date" so that we could set a trigger on it (eg. If more than 48 hours, send an email to the homeowner")

![img_4148 2](https://user-images.githubusercontent.com/1536431/44352436-568b5900-a472-11e8-9114-07514bf391f4.jpg)
![img_4150 2](https://user-images.githubusercontent.com/1536431/44352442-5c813a00-a472-11e8-9a56-aeafd5c7b6aa.jpg)

**Comment by FlyingDiver** [comment]
The last_update is a device state, so you could test that during your daily reading schedule and do a notification.

<img width="558" alt="screen shot 2018-08-20 at 12 50 10 pm" src="https://user-images.githubusercontent.com/72976/44354350-a28ccc80-a477-11e8-83bd-ae9e93659d94.png">

**Comment by dstrickler** [comment]
That's just what I was looking for - thanks! I can't wait to get this up and running. Anxiously awaiting my next sensor read...

**Comment by FlyingDiver** [comment]
You can force one by pressing the buttons on the device, I think.

**Comment by dstrickler** [comment]
I reset the sensor, and you're right, it phoned home. The "last update" is about 5 minutes old.

I ran the plugin, and got the same result in the log. I see an "_ssl.c" string in there. Could this be an SSL error? It is working for you, so that says no to me...
I did check the username/pass, and I can log into their website with it.

```
TankUtility                     Getting tank data from TankUtility server...
TankUtility Debug               tuLogin failure, request url = https://data.tankutility.com/api/getToken
TankUtility Error               tuLogin failure, RequestException: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
TankUtility Debug               getDevices: TankUtility Login Failure

```

**Comment by FlyingDiver** [comment]
Hmm.  What version macOS are you running?  I wonder if this is a manifestation of the TLS issue with Python.

**Comment by dstrickler** [comment]
I also noticed that the names for the polling are sligntly different from the docs. Just thought I'd let you know.
<img width="945" alt="tankutility_actions_and_banners_and_alerts" src="https://user-images.githubusercontent.com/1536431/44358853-2cdb2d80-a484-11e8-9351-ba49d8696217.png">

**Comment by dstrickler** [comment]
Good point on the Python. I'm running Mac OSX 10.9.5, and Python looks like 2.7.5

**Comment by FlyingDiver** [comment]
Yeah, you've got the old Python.  There's some threads on the forums about that.  The only fix I know is to upgrade macOS.

**Comment by dstrickler** [comment]
What version would you like to see installed?

**Comment by FlyingDiver** [comment]
My Indigo server is running Sierra.  I know that works.

**Comment by dstrickler** [comment]
Unfortunately, I can't upgrade the O/S as my MacMini is too old. One more reason for me to upgrade! Thanks for all the help. I'll check back in when I've upgraded the hardware.
